# This role will be used to reboot the mysql restore nodes
---
- name: Stop MySQL
  become: true
  shell: "systemctl stop mysql && sleep 5"

- name: Perform reboot
  reboot:

- name: Wait for mysql to fully start
  become: true
  shell: "sleep 15"

- name: Check mysql status
  become: true
  shell: "systemctl status mysql"
